import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import Banner from "./../components/Banner";
import { elementDragControls } from "framer-motion/types/gestures/drag/VisualElementDragControls";
const Home: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {props.bannerData ? (
          <Banner heading={props.heading} data={props.bannerData} />
        ) : (
          ""
        )}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  let bannerData = [];
  try {
    const response = await axios.get(
      "http://localhost:1337/api/banners/?populate=*"
    );
    bannerData = response.data.data.map((element: any) => {
      console.log(element.attributes.image.data.attributes.url);
      return {
        ...element.attributes,
        id: element.id,
        image: element.attributes.image.data.attributes.url,
      };
    });
  } catch (error) {
    console.error(error);
  }

  return {
    props: {
      bannerData: bannerData,
    },
  };
}
